import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Home,CalendarDays,ArrowRight,MapPin,Users,TrendingUp,Bell,Clock,ChevronRight,Briefcase,UserRound,BarChart3,Repeat2,Cake,Star,AlertTriangle,Megaphone}from'lucide-react';import'./styles.css';

const sessions=[
{id:1,day:'TODAY',date:'24 SEP',time:'5:30 PM',studio:'Kings Cross',brand:"Barry's",type:'Total Body · Upper Focus',booked:39,cap:50,state:'ON TRACK',expected:38,delta:'+3%',tone:'good'},
{id:2,day:'FRI',date:'25 SEP',time:'7:00 AM',studio:'Martin Place',brand:"Barry's",type:'Total Body',booked:44,cap:50,state:'STRONG',expected:39,delta:'+13%',tone:'strong'},
{id:3,day:'SAT',date:'26 SEP',time:'10:00 AM',studio:'Surry Hills',brand:"Barry's",type:'Total Body',booked:21,cap:50,state:'NEEDS ATTENTION',expected:29,delta:'−28%',tone:'warn'},
{id:4,day:'SUN',date:'27 SEP',time:'9:30 AM',studio:'Bondi',brand:'Arc Pilates',type:'Reformer',booked:11,cap:14,state:'ON TRACK',expected:10,delta:'+10%',tone:'good'}];

function Pill({children,tone='good'}:{children:React.ReactNode,tone?:string}){return <span className={'pill '+tone}>{children}</span>}
function SessionCard({s,onClick}:{s:any,onClick:()=>void}){return <button className="session" onClick={onClick}><div className="datebox"><b>{s.day}</b><span>{s.date}</span></div><div className="sessionbody"><div className="eyebrow">{s.brand} · {s.studio}</div><h3>{s.time}</h3><p>{s.type}</p><div className="sessionmeta"><span><Users size={14}/>{s.booked}/{s.cap}</span><Pill tone={s.tone}>{s.state}</Pill></div></div><ChevronRight className="chev" size={19}/></button>}

function HomeScreen({open}:{open:(s:any)=>void}){return <><header><div><div className="eyebrow">THURSDAY · 24 SEPTEMBER</div><h1>Good afternoon,<br/>Nayan.</h1></div><button className="icon"><Bell size={20}/><i/></button></header><section className="hero"><div className="heroTop"><div><div className="eyebrow pale">NEXT CLASS</div><h2>5:30 PM</h2><p><MapPin size={15}/> Kings Cross · Total Body</p></div><div className="ring"><b>39</b><span>/50</span></div></div><div className="heroBottom"><span>Bookings are <b>on track</b> for this point</span><button onClick={()=>open(sessions[0])}>View class <ArrowRight size={15}/></button></div></section><div className="sectionhead"><h2>This week</h2><span>4 classes · 3 studios</span></div><div className="week">{sessions.slice(1).map(s=><SessionCard key={s.id}s={s}onClick={()=>open(s)}/>)}</div><div className="sectionhead"><h2>Performance</h2><button>Last 8 weeks</button></div><div className="metrics"><div><span>UTILISATION</span><b>87%</b><em>↑ 4% vs prior</em></div><div><span>30D RETENTION</span><b>64%</b><em>↑ 6% vs benchmark</em></div><div><span>CLIENT SCORE</span><b>9.2</b><em>128 responses</em></div></div></>}

function Schedule({open}:{open:(s:any)=>void}){return <><header><div><div className="eyebrow">MY WORK</div><h1>Schedule</h1></div><div className="company"><Briefcase size={15}/> All companies</div></header><div className="notice"><Repeat2 size={17}/><div><b>One schedule. Every studio.</b><span>Your employers only see availability within their own organisation.</span></div></div><div className="week all">{sessions.map(s=><SessionCard key={s.id}s={s}onClick={()=>open(s)}/>)}</div></>}

function ClassDetail({s,back}:{s:any,back:()=>void}){const pct=Math.round(s.booked/s.cap*100);return <><button className="back"onClick={back}>← Schedule</button><div className="detailHead"><div className="eyebrow">{s.brand.toUpperCase()} · {s.studio.toUpperCase()}</div><h1>{s.day==='TODAY'?'Today':s.day}, {s.time}</h1><p>{s.type}</p></div><div className={'demand '+s.tone}><div><span>DEMAND NOW</span><b>{s.booked}<small> / {s.cap}</small></b><em>{pct}% filled</em></div><div><span>EXPECTED NOW</span><b>{s.expected}</b><em>{s.delta} vs trajectory</em></div></div>{s.tone==='warn'&&<div className="alert"><AlertTriangle size={19}/><div><b>This class needs attention</b><span>Bookings are 8 below the usual trajectory at this lead time.</span></div><button><Megaphone size={15}/> Mark promoted</button></div>}<div className="sectionhead"><h2>Booking trajectory</h2><span>Comparable slot history</span></div><div className="chart"><div className="gridline l1"/><div className="gridline l2"/><svg viewBox="0 0 400 120" preserveAspectRatio="none"><path d="M0 108 C60 98 80 78 130 70 S210 48 260 34 S340 14 400 8" className="expected"/><path d={s.tone==='warn'?"M0 110 C60 102 90 92 135 88 S215 78 260 69 S330 55 400 48":"M0 110 C60 99 90 82 135 73 S215 50 260 38 S330 19 400 11"} className="actual"/></svg><div className="axis"><span>−7d</span><span>−3d</span><span>−24h</span><span>START</span></div></div><div className="sectionhead"><h2>Class roster</h2><button>View all {s.booked}</button></div><div className="roster"><div><div className="avatar">SA</div><p><b>Sarah A.</b><span><Cake size={13}/> Birthday today</span></p><ChevronRight size={17}/></div><div><div className="avatar">JM</div><p><b>James M.</b><span><Star size={13}/> 100th class milestone</span></p><ChevronRight size={17}/></div><div><div className="avatar">AL</div><p><b>Alex L.</b><span>First class with you</span></p><ChevronRight size={17}/></div></div><div className="sectionhead"><h2>This timeslot</h2><span>Last 8 weeks</span></div><div className="slotstats"><div><b>89%</b><span>Avg utilisation</span></div><div><b>67%</b><span>30d retention</span></div><div><b>+5%</b><span>vs studio benchmark</span></div></div></>}

function App(){const[tab,setTab]=useState('home');const[selected,setSelected]=useState<any>(null);const open=(s:any)=>setSelected(s);return <div className="shell"><main>{selected?<ClassDetail s={selected}back={()=>setSelected(null)}/>:tab==='home'?<HomeScreen open={open}/>:tab==='schedule'?<Schedule open={open}/>:<div className="placeholder"><BarChart3/><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1><p>Next build slice.</p></div>}</main>{!selected&&<nav>{[['home',Home],['schedule',CalendarDays],['shifts',Repeat2],['performance',TrendingUp],['profile',UserRound]].map(([n,I]:any)=><button key={n}className={tab===n?'active':''}onClick={()=>setTab(n)}><I size={20}/><span>{n}</span></button>)}</nav>}</div>}createRoot(document.getElementById('root')!).render(<App/>);