import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Home,CalendarDays,ArrowRight,MapPin,Users,TrendingUp,Bell,ChevronRight,Briefcase,UserRound,BarChart3,Repeat2,Cake,Star,AlertTriangle,Megaphone,Clock3,Check,Layers3,MessageCircle}from'lucide-react';import'./styles.css';

const sessions=[
{id:1,day:'TODAY',date:'24 SEP',time:'5:30 PM',studio:'Kings Cross',brand:"Barry's",type:'Total Body · Upper Focus',booked:39,cap:50,state:'ON TRACK',expected:38,delta:'+3%',tone:'good',days:0},
{id:2,day:'FRI',date:'25 SEP',time:'7:00 AM',studio:'Martin Place',brand:"Barry's",type:'Total Body',booked:44,cap:50,state:'STRONG',expected:39,delta:'+13%',tone:'strong',days:1},
{id:3,day:'SAT',date:'26 SEP',time:'10:00 AM',studio:'Surry Hills',brand:"Barry's",type:'Total Body',booked:21,cap:50,state:'NEEDS ATTENTION',expected:29,delta:'−28%',tone:'warn',days:2},
{id:4,day:'SUN',date:'27 SEP',time:'9:30 AM',studio:'Bondi',brand:'Arc Pilates',type:'Reformer',booked:11,cap:14,state:'ON TRACK',expected:10,delta:'+10%',tone:'good',days:3},
{id:5,day:'SAT',date:'03 OCT',time:'8:00 AM',studio:'Kings Cross',brand:"Barry's",type:'Total Body',booked:31,cap:50,state:'ON TRACK',expected:30,delta:'+3%',tone:'good',days:9}];
const openShifts=[
{id:'a',date:'SAT · 03 OCT',studio:'Kings Cross',brand:"Barry's",classes:['8:00 AM','9:00 AM','10:00 AM'],type:'Total Body',mode:'PREFER TOGETHER',note:'Full bundle preferred, but you can submit availability for individual classes.',eligible:true},
{id:'b',date:'TUE · 06 OCT',studio:'Martin Place',brand:"Barry's",classes:['12:00 PM'],type:'Total Body · Lower Focus',mode:'SINGLE',note:'',eligible:true},
{id:'c',date:'WED · 07 OCT',studio:'Bondi',brand:'Arc Pilates',classes:['6:30 AM','7:30 AM'],type:'Reformer',mode:'KEEP TOGETHER',note:'Both classes must be covered together.',eligible:false,reason:'Conflicts with another class in your MyTeam schedule.'}];

function Pill({children,tone='good'}:{children:React.ReactNode,tone?:string}){return <span className={'pill '+tone}>{children}</span>}
function SessionCard({s,onClick}:{s:any,onClick:()=>void}){return <button className="session" onClick={onClick}><div className="datebox"><b>{s.day}</b><span>{s.date}</span></div><div className="sessionbody"><div className="eyebrow">{s.brand} · {s.studio}</div><h3>{s.time}</h3><p>{s.type}</p><div className="sessionmeta"><span><Users size={14}/>{s.booked}/{s.cap}</span><Pill tone={s.tone}>{s.state}</Pill></div></div><ChevronRight className="chev" size={19}/></button>}

function HomeScreen({open}:{open:(s:any)=>void}){return <><header><div><div className="eyebrow">THURSDAY · 24 SEPTEMBER</div><h1>Good afternoon,<br/>Nayan.</h1></div><button className="icon"><Bell size={20}/><i/></button></header><section className="hero"><div className="heroTop"><div><div className="eyebrow pale">NEXT CLASS</div><h2>5:30 PM</h2><p><MapPin size={15}/> Kings Cross · Total Body</p></div><div className="ring"><b>39</b><span>/50</span></div></div><div className="heroBottom"><span>Bookings are <b>on track</b> for this point</span><button onClick={()=>open(sessions[0])}>View class <ArrowRight size={15}/></button></div></section><div className="sectionhead"><h2>This week</h2><span>4 classes · 3 studios</span></div><div className="week">{sessions.slice(1,4).map(s=><SessionCard key={s.id}s={s}onClick={()=>open(s)}/>)}</div><div className="sectionhead"><h2>Performance</h2><button>Last 8 weeks</button></div><div className="metrics"><div><span>UTILISATION</span><b>87%</b><em>↑ 4% vs prior</em></div><div><span>30D RETENTION</span><b>64%</b><em>↑ 6% vs benchmark</em></div><div><span>CLIENT SCORE</span><b>9.2</b><em>128 responses</em></div></div></>}

function Schedule({open}:{open:(s:any)=>void}){return <><header><div><div className="eyebrow">MY WORK</div><h1>Schedule</h1></div><div className="company"><Briefcase size={15}/> All companies</div></header><div className="notice"><Repeat2 size={17}/><div><b>One schedule. Every studio.</b><span>Your employers only see availability within their own organisation.</span></div></div><div className="week all">{sessions.map(s=><SessionCard key={s.id}s={s}onClick={()=>open(s)}/>)}</div></>}

function Shifts({open}:{open:(s:any)=>void}){const[view,setView]=useState('available');const requests=[{id:'r1',date:'SAT · 03 OCT',time:'8:00 AM',studio:'Kings Cross',type:'Total Body',status:'OPEN',responses:4},{id:'r2',date:'SUN · 11 OCT',time:'9:30 AM',studio:'Bondi',type:'Reformer',status:'FILLED',responses:2}];const apps=[{id:'p1',date:'SAT · 03 OCT',studio:'Kings Cross',classes:['8:00 AM','9:00 AM','10:00 AM'],status:'PENDING',note:'Full bundle availability submitted'},{id:'p2',date:'TUE · 29 SEP',studio:'Martin Place',classes:['12:00 PM'],status:'APPROVED',note:'Cover confirmed · source schedule pending update'},{id:'p3',date:'SUN · 20 SEP',studio:'Surry Hills',classes:['10:00 AM'],status:'NOT SELECTED',note:'Shift was filled by another instructor'}];return <><header><div><div className="eyebrow">COVERS & OPPORTUNITIES</div><h1>Shifts</h1></div>{view==='available'&&<Pill tone="strong">3 OPEN</Pill>}</header><div className="shiftTabs"><button className={view==='available'?'active':''}onClick={()=>setView('available')}>Available</button><button className={view==='requests'?'active':''}onClick={()=>setView('requests')}>My requests</button><button className={view==='applications'?'active':''}onClick={()=>setView('applications')}>Applications</button></div>{view==='available'?<div className="shiftList">{openShifts.map(x=><button className={'shiftCard '+(!x.eligible?'disabled':'')} onClick={()=>x.eligible&&open(x)} key={x.id}><div className="shiftTop"><div><div className="eyebrow">{x.brand} · {x.studio}</div><h3>{x.date}</h3><p>{x.type}</p></div>{x.classes.length>1&&<div className="bundle"><Layers3 size={14}/>{x.classes.length} classes</div>}</div><div className="times">{x.classes.map(t=><span key={t}>{t}</span>)}</div>{x.mode!=='SINGLE'&&<div className="bundleMode">{x.mode.replaceAll('_',' ')}</div>}<div className="shiftFoot">{x.eligible?<span>You're eligible to apply</span>:<span><AlertTriangle size={13}/>{x.reason}</span>}<ChevronRight size={17}/></div></button>)}</div>:view==='requests'?<div className="shiftList">{requests.map(r=><div className="trackingCard"key={r.id}><div><div className="eyebrow">YOUR COVER REQUEST · {r.studio}</div><h3>{r.date} · {r.time}</h3><p>{r.type}</p></div><div className="trackRow"><Pill tone={r.status==='OPEN'?'warn':'strong'}>{r.status}</Pill><span>{r.status==='OPEN'?r.responses+' instructors available':'Replacement confirmed'}</span></div>{r.status==='OPEN'&&<div className="progress"><i style={{width:'66%'}}/></div>}</div>)}</div>:<div className="shiftList">{apps.map(a=><div className="trackingCard"key={a.id}><div className="eyebrow">YOUR APPLICATION · {a.studio}</div><h3>{a.date}</h3><div className="times">{a.classes.map(t=><span key={t}>{t}</span>)}</div><div className="trackRow"><Pill tone={a.status==='APPROVED'?'strong':a.status==='PENDING'?'good':'muted'}>{a.status}</Pill><span>{a.note}</span></div></div>)}</div>}</>}

function ShiftDetail({x,back}:{x:any,back:()=>void}){const initial=x.mode==='KEEP TOGETHER'?x.classes:x.classes;const[selected,setSelected]=useState<string[]>(initial);const[done,setDone]=useState(false);const toggle=(t:string)=>{if(x.mode==='KEEP TOGETHER')return;setSelected(v=>v.includes(t)?v.filter(a=>a!==t):[...v,t])};if(done)return <div className="success"><div className="successIcon"><Check/></div><div className="eyebrow">AVAILABILITY SUBMITTED</div><h1>You're in.</h1><p>Management can now see your availability. This does not change the live schedule until they approve the cover.</p><button className="primary" onClick={back}>Back to shifts</button></div>;return <><button className="back"onClick={back}>← Available shifts</button><div className="detailHead"><div className="eyebrow">{x.brand.toUpperCase()} · {x.studio.toUpperCase()}</div><h1>{x.date}</h1><p>{x.type}</p></div>{x.classes.length>1&&<div className="notice bundleNotice"><Layers3 size={18}/><div><b>{x.mode==='KEEP TOGETHER'?'Keep together':'Bundle preferred'}</b><span>{x.note}</span></div></div>}<div className="sectionhead"><h2>Your availability</h2><span>{selected.length}/{x.classes.length} selected</span></div><div className="selectTimes">{x.classes.map((t:string)=><button key={t} onClick={()=>toggle(t)} className={selected.includes(t)?'selected':''}><span><Clock3 size={17}/>{t}</span><i>{selected.includes(t)&&<Check size={14}/>}</i></button>)}</div>{x.mode==='PREFER TOGETHER'&&selected.length<x.classes.length&&selected.length>0&&<div className="micro"><b>Partial availability is okay.</b> Management will see full-bundle applicants first, but can split this cover.</div>}<div className="eligibility"><div><Check size={15}/><span>No schedule conflict</span></div><div><Check size={15}/><span>Travel buffer works</span></div><div><Check size={15}/><span>Qualified for this class</span></div></div><button className="primary" disabled={!selected.length} onClick={()=>setDone(true)}>Submit availability <ArrowRight size={16}/></button><p className="fineprint">Submitting availability does not assign the class. You'll be notified after management makes a decision.</p></>}

function ClassDetail({s,back}:{s:any,back:()=>void}){const pct=Math.round(s.booked/s.cap*100);const[cover,setCover]=useState(false);const urgent=s.days<=7;if(cover)return <CoverFlow s={s}back={()=>setCover(false)}/>;return <><button className="back"onClick={back}>← Schedule</button><div className="detailHead"><div className="eyebrow">{s.brand.toUpperCase()} · {s.studio.toUpperCase()}</div><h1>{s.day==='TODAY'?'Today':s.day}, {s.time}</h1><p>{s.type}</p></div><button className={'coverButton '+(urgent?'urgent':'')} onClick={()=>setCover(true)}><Repeat2 size={16}/>{urgent?'Need a cover?':'Request cover'}<ChevronRight size={16}/></button><div className={'demand '+s.tone}><div><span>DEMAND NOW</span><b>{s.booked}<small> / {s.cap}</small></b><em>{pct}% filled</em></div><div><span>EXPECTED NOW</span><b>{s.expected}</b><em>{s.delta} vs trajectory</em></div></div>{s.tone==='warn'&&<div className="alert"><AlertTriangle size={19}/><div><b>This class needs attention</b><span>Bookings are 8 below the usual trajectory at this lead time.</span></div><button><Megaphone size={15}/> Mark promoted</button></div>}<div className="sectionhead"><h2>Booking trajectory</h2><span>Comparable slot history</span></div><div className="chart"><svg viewBox="0 0 400 120" preserveAspectRatio="none"><path d="M0 108 C60 98 80 78 130 70 S210 48 260 34 S340 14 400 8" className="expected"/><path d={s.tone==='warn'?"M0 110 C60 102 90 92 135 88 S215 78 260 69 S330 55 400 48":"M0 110 C60 99 90 82 135 73 S215 50 260 38 S330 19 400 11"} className="actual"/></svg><div className="axis"><span>−7d</span><span>−3d</span><span>−24h</span><span>START</span></div></div><div className="sectionhead"><h2>Class roster</h2><button>View all {s.booked}</button></div><div className="roster"><div><div className="avatar">SA</div><p><b>Sarah A.</b><span><Cake size={13}/> Birthday today</span></p><ChevronRight size={17}/></div><div><div className="avatar">JM</div><p><b>James M.</b><span><Star size={13}/> 100th class milestone</span></p><ChevronRight size={17}/></div></div></>}

function CoverFlow({s,back}:{s:any,back:()=>void}){const urgent=s.days<=7;const[done,setDone]=useState(false);if(done)return <div className="success"><div className="successIcon"><Check/></div><div className="eyebrow">COVER REQUESTED</div><h1>Request posted.</h1><p>Eligible instructors can now submit availability. Management will still approve the final cover and update the source schedule.</p><button className="primary" onClick={back}>Done</button></div>;return <><button className="back"onClick={back}>← Class details</button><div className="detailHead"><div className="eyebrow">COVER</div><h1>{urgent?'Contact management':'Request a cover'}</h1><p>{s.day} · {s.date} · {s.time}<br/>{s.studio} · {s.type}</p></div>{urgent?<><div className="cutoff"><AlertTriangle/><div><b>This class is within 7 days.</b><span>To prevent last-minute unattended cover posts, contact your manager directly. MyTeam won't post this automatically.</span></div></div><button className="primary"><MessageCircle size={16}/> Message manager</button></>:<><div className="notice"><Repeat2 size={17}/><div><b>More than 7 days away</b><span>This class is eligible for the normal MyTeam cover workflow.</span></div></div><label className="field">Optional note<textarea placeholder="Anything management or the team should know?"/></label><button className="primary" onClick={()=>setDone(true)}>Post cover request <ArrowRight size={16}/></button><p className="fineprint">Your class remains your responsibility until management confirms a replacement.</p></>}</>}

function App(){const[tab,setTab]=useState('home');const[selected,setSelected]=useState<any>(null);const[shift,setShift]=useState<any>(null);const open=(s:any)=>setSelected(s);return <div className="shell"><main>{shift?<ShiftDetail x={shift}back={()=>setShift(null)}/>:selected?<ClassDetail s={selected}back={()=>setSelected(null)}/>:tab==='home'?<HomeScreen open={open}/>:tab==='schedule'?<Schedule open={open}/>:tab==='shifts'?<Shifts open={setShift}/>:<div className="placeholder"><BarChart3/><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1><p>Next build slice.</p></div>}</main>{!selected&&!shift&&<nav>{[['home',Home],['schedule',CalendarDays],['shifts',Repeat2],['performance',TrendingUp],['profile',UserRound]].map(([n,I]:any)=><button key={n}className={tab===n?'active':''}onClick={()=>setTab(n)}><I size={20}/><span>{n}</span></button>)}</nav>}</div>}createRoot(document.getElementById('root')!).render(<App/>);